# Generated by Django 5.0.7 on 2024-08-02 05:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calc", "0003_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="ustomer",
            new_name="customer",
        ),
    ]
